{
 "title": "Traefik Opentelemetry",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS (1m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"traefik\"}[1m]))"
    }
   ]
  },
  {
   "title": "p95 latency (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(\r\n  0.95,\r\n  ({service_name=\"traefik\"} | json Duration | unwrap Duration)[5m]\r\n) by (service_name) / 1e6\r\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (entrypoint) (traefik_open_connections_ratio)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Total Config Reload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traefik_config_reloads_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"traefik\"}  |= \"RequestProtocol\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum_over_time({service_name=\"traefik\"}|= \"RequestProtocol\" | json | OriginStatus=200 | unwrap DownstreamContentSize |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "| Code | Status | Meaning |\n| :--- | :--- | :--- |\n| **200** | 🟢 OK | Success |\n| **302** | 🔵 Found | Temporary redirect |\n| **304** | 🔵 Not Modified | Loaded from Cache |\n| **400** | 🟠 Bad Request | Malformed syntax / Validation error |\n| **401** | 🟠 Unauthorized | Invalid or missing API key |\n| **403** | 🟠 Forbidden | Valid auth, but permissions denied |\n| **404** | 🟠 Not Found | Resource does not exist |\n| **499** | 🔴 Client Closed | Browser canceled request early |\n| **502** | 🔴 Bad Gateway | Upstream server is down/unreachable |"
   }
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(traefik_service_requests_total{protocol=\"http\"}[1m])) > 0",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (DownstreamStatus) (\r\n  count_over_time(\r\n    {service_name=\"traefik\"}\r\n      |~ \"^\\\\{\"\r\n      | json\r\n      | __error__=\"\"\r\n      | DownstreamStatus!=\"0\"\r\n      | DownstreamStatus!=\"\"\r\n  [$__range])\r\n)\r\n",
     "legendFormat": "HTTP Status: {{DownstreamStatus}}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(20,\r\n  sum by (request_Cf_Ipcountry) (\r\n    count_over_time(\r\n      {service_name=\"traefik\"} |= \"RequestProtocol\"\r\n      | json | __error__=\"\"\r\n      | request_Cf_Ipcountry=~\"[A-Z]{2}\"\r\n    [$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{request_Cf_Ipcountry}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum)\r\n/\r\nsum(traefik_service_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(20,\r\n  sum by (request_X_Real_Ip) (\r\n    count_over_time(\r\n      {service_name=\"traefik\"} |= \"RequestProtocol\"\r\n      | json | __error__=\"\"\r\n      | request_Cf_Ipcountry=~\"[A-Z]{2}\"\r\n    [$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{request_Cf_Ipcountry}}"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Access Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"traefik\"} |= \"RequestProtocol\" | json  | line_format \"Status: {{.OriginStatus}} Client From {{.request_Cf_Ipcountry}} IP {{.request_Cf_Connecting_Ip}} {{.request_X_Real_Ip}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}} Route To {{.ServiceAddr}}\""
    }
   ]
  },
  {
   "title": " Error Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"traefik\"} \r\n| detected_level=\"info\" \r\n| DownstreamStatus != 200\r\n| DownstreamStatus!=\"0\"\r\n| OriginStatus!=\"0\"\r\n| DownstreamStatus!=\"\"\r\n| line_format \"Status: {{.OriginStatus}} Client From {{.request_Cf_Ipcountry}} IP {{.request_Cf_Connecting_Ip}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}} Route To {{.ServiceAddr}}\""
    }
   ]
  },
  {
   "title": "traefik service requests_total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    { "expr": "traefik_service_requests_total", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Requests per Router",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(router) (rate(traefik_router_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration per Router",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traefik_router_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Bytes per Router",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "label_replace(sum by(service) (rate(traefik_service_responses_bytes_total[$__rate_interval])), \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Duration per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_request_duration_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(entrypoint) (rate(traefik_entrypoint_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}